# Generated by Django 5.1.3 on 2024-12-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subscription'),
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('Cash', 'наличные'), ('Transfer', 'перевод')], max_length=50, verbose_name='тип оплаты')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('payment_url', models.URLField(blank=True, max_length=450, null=True, verbose_name='Ссылка на оплату')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
